/PREP7
*ask,E,Youngs modulus (MPa),1
*ask,ro,density (tn/mm3),1e-9
*ask,nu,poisson ratio,0.3

mp,ex,1,E
mp,nuxy,1,nu
mp,dens,1,ro

ET,1,plane183

lesize,all,Le

aatt,1,,1
amesh,all
allsel

*get,nmax,node,,num,max
*get,emax,elem,,num,max

NGEN,2,nmax+1,P51X, , ,dist, , ,1,
FLST,5,emax+1,2,ORDE,2 
FITEM,5,1   
FITEM,5,-emax-1

FLST,5,emax+1,2,ORDE,2 
FITEM,5,1   
FITEM,5,-emax-1
ENGEN,emax+1,2,nmax+1,P51X, , , , , , , ,dist, , ,   

finish